"""
This module provides a Streamlit web interface for a CSV data analysis tool.

It allows users to upload a CSV file, enter a query, and view the response
generated by the query agent.
"""

from typing import IO

import streamlit as st

from utils import query_agent


def validate_inputs(uploaded_file: IO[bytes] | None, query: str) -> bool:
    """
    Validates the user's inputs.

    Args:
        uploaded_file: The uploaded CSV file.
        query: The user's query.

    Returns:
        True if the inputs are valid, False otherwise.
    """
    if uploaded_file is None:
        st.error("Please upload a CSV file")
        return False
    if query == "":
        st.error("Please enter a query")
        return False
    return True


def main() -> None:
    """
    The main function of the application.
    """
    st.title("CSV Data Analysis Tool")
    st.header("Upload a CSV file and analyze its contents.")

    uploaded_file = st.file_uploader("Choose a CSV file", type="csv")
    query = st.text_input("Enter your query")
    button = st.button("Generate Response")

    if button and validate_inputs(uploaded_file, query):
        with st.spinner("Generating response..."):
                response = query_agent(uploaded_file, query)
        st.write(response)


if __name__ == "__main__":
    main()